#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==> Installing flatpak apps from flatpak.txt..."
if [[ -f "$SCRIPT_DIR/flatpaks.txt" ]]; then
    flatpak install -y $(<"$SCRIPT_DIR/flatpaks.txt")
else
    echo "$SCRIPT_DIR/flatpaks.txt not found!"
fi

